package main

var fioConfigs = []fioConfig{
	{
		Filename:       "iops_and_bw_for_rand_reads_and_writes.file",
		Size:           "1GB",
		Direct:         true,
		RW:             "randread",
		BS:             "4k",
		IOEngine:       "libaio",
		IODepth:        256,
		NumJobs:        8,
		TimeBased:      true,
		GroupReporting: true,
		Name:           "iops_and_bw_for_rand_reads_and_writes",
		Runtime:        10,
		ETANewline:     1,
	},
	{
		Filename:       "iops_and_bw_for_seq_reads.file",
		Size:           "5GB",
		Direct:         true,
		RW:             "randread",
		BS:             "4k",
		IOEngine:       "libaio",
		IODepth:        256,
		NumJobs:        8,
		TimeBased:      true,
		GroupReporting: true,
		Name:           "iops_and_bw_for_seq_reads",
		Runtime:        10,
		ETANewline:     1,
	},
	{
		Filename:       "throughput_for_rand_reads.file",
		Size:           "10GB",
		Direct:         true,
		RW:             "randread",
		BS:             "64k",
		IOEngine:       "libaio",
		IODepth:        64,
		NumJobs:        8,
		TimeBased:      true,
		GroupReporting: true,
		Name:           "throughput_for_rand_reads",
		Runtime:        10,
		ETANewline:     1,
	},
	{
		Filename:       "throughput_for_rand_reads_and_writes.file",
		Size:           "20GB", //50GB
		Direct:         true,
		RW:             "randrw",
		BS:             "64k",
		IOEngine:       "libaio",
		IODepth:        64,
		NumJobs:        8,
		TimeBased:      true,
		GroupReporting: true,
		Name:           "throughput_for_rand_reads_and_writes",
		Runtime:        10,
		ETANewline:     1,
	},
	{
		Filename:       "throughput_for_seq_reads.file",
		Size:           "10GB", //10GB
		Direct:         true,
		RW:             "randrw",
		BS:             "64k",
		IOEngine:       "libaio",
		IODepth:        64,
		NumJobs:        8,
		TimeBased:      true,
		GroupReporting: true,
		Name:           "throughput_for_seq_reads",
		Runtime:        10,
		ETANewline:     1,
	},
	{
		Filename:       "latency_for_random_reads.file",
		Size:           "10GB", //10GB
		Direct:         true,
		RW:             "randread",
		BS:             "4k",
		IOEngine:       "libaio",
		IODepth:        1,
		NumJobs:        4, //50% of cores available
		TimeBased:      true,
		GroupReporting: true,
		Name:           "latency_for_random_reads",
		Runtime:        10,
		ETANewline:     1,
	},
	{
		Filename:       "latency_for_random_reads_and_writes.file",
		Size:           "10GB", //10GB
		Direct:         true,
		RW:             "randrw",
		BS:             "4k",
		IOEngine:       "libaio",
		IODepth:        1,
		NumJobs:        4, //50% of cores available
		TimeBased:      true,
		GroupReporting: true,
		Name:           "latency_for_random_reads_and_writes",
		Runtime:        10,
		ETANewline:     1,
	},
}
